language: python
sudo: required
cache:
  bundler: true
  directories:
    - $HOME/docker
services:
  - docker
python:
  - "3.5"
  - "3.6"
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker pull spotify/kafka
  - docker run -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=0.0.0.0 --env ADVERTISED_PORT=9092 spotify/kafka
  - docker ps -a
install:
  - "pip install -r requirements.txt"
  - "pip install ."
script:
  - "flake8 franz"
  - "py.test"
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
