# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    steps:
      - checkout

      - install_python_versions:
        command: |
          pyenv install 3.5.3
          pyenv install 3.6.3
          pyenv install 3.7.0
          pyenv virtualenv franz 3.5.3
          pyenv local franz 3.5.3 3.6.3 3.7.0

      - run:
          name: install dependencies
          command: |
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
